#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#
#modify by qiuyigui 2015-02-15
#obj-y	:= smdkc100.o
obj-y	:= smdkv210.o
obj-$(CONFIG_SAMSUNG_ONENAND)	+= onenand.o
obj-y	+= lowlevel_init.o
obj-y	+= mem_setup.o#add by qiuyigui 2015-02-15
